export enum OrderStatusTypes {
  CREATED = 'CREATED',
  CANCELLED = 'CANCELLED',
  ASSIGNED = 'ASSIGNED',
  PICKED_UP = 'PICKED_UP',
  DELIVERED = 'DELIVERED',
  CONFIRMED = 'CONFIRMED',
  REJECTED = 'REJECTED',
  PAID = 'PAID',
  COMPLETED = 'COMPLETED',
  //#region not used
  ARCHIVED = 'ARCHIVED',
  REPORTED = 'REPORTED',
  //#endregion
}
