apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: emilevi4/avpz.mono_api
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: DB_HOST
              value: mono-api-postgres-srv
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_NAME
              value: db
            - name: API_URL
              value: http://www.emilevi4.store
            - name: CLIENT_URL
              value: http://www.emilevi4.store
          resources:
            limits:
              cpu: '1'
              memory: '512Mi'
            requests:
              cpu: '100m'
              memory: '256Mi'

---
apiVersion: v1
kind: Service
metadata:
  name: api-srv
spec:
  selector:
    app: api
  ports:
    - name: api
      protocol: TCP
      port: 3000
      targetPort: 3000
